# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75d6fe0c93b52e868e0135b20d80fca3104ed94bb34ccf12fa279bb4fce0bcf9e3ee065f9cde49908203e99a5f77e5f17e832091e8f618d4e3145d12db5fac1a

test:
  secret_key_base: 33621c66eb12bf2d3309a58df8a874bfc8a046876238d5dffa9d9fa505bfe882a28949b0900841ecadcbf78be73a067961c3cea10b47bab61df6e7b33e655faa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
